### PR TITLE
feat(cli): report agent sessions separately from terminals

### LINKED ISSUE #6980: [feat] Expose provider-neutral resumable agent identity and liveness from the CLI
### What problem are you trying to solve?

Automation can create and steer a terminal agent with the Superset CLI, but it cannot reliably park that agent and later resume the same conversation.

`superset agents create --json` returns the Superset terminal `sessionId`. `--resume-session`, however, is passed to the selected provider preset and therefore expects that provider conversation ID. Passing the returned terminal ID to `claude --resume`, `codex resume`, or another provider fails. The provider may exit while the shell remains open, so `superset terminals list` still reports a live terminal even though no agent is running.

This creates two false claims for integrations:
- a terminal ID is stored as though it were resumable agent identity;
- an idle shell is reported as active agent execution.

The problem is cross-provider. Built-in presets declare resume arguments for Claude, Codex, Amp, Gemini, Mastra, OpenCode, Pi, Kimi, Copilot, Vibe, Grok, Cursor and Droid. Integrations should not parse provider files or implement a separate adapter for each one.

### Current foundation

Superset already has the correct ownership boundary:

- `terminal_agent_bindings` stores `agent_id`, `agent_session_id`, `last_event_type`, `last_event_at`, `ended_at`, and `end_reason`.
- `TerminalAgentBinding` already carries `agentSessionId`.
- Agent hook handling covers Claude, Codex, and other hook-capable runtimes.
- `agents.run` already accepts `resumeSessionId` and builds the provider command from the selected preset `resumeArgs`.

The missing part is a supported CLI/API response that exposes this state to external orchestrators.

### Proposed contract

Return terminal identity and agent identity separately from `superset agents create --json`, and expose the same fields from a supported read/list command:

```json
{
  "kind": "terminal",
  "terminalId": "superset-terminal-id",
  "agent": {
    "presetId": "codex",
    "sessionId": "opaque-provider-session-id",
    "resumable": true,
    "state": "working",
    "lastEventType": "Start",
    "lastEventAt": "2026-08-29T00:00:00Z",
    "endedAt": null,
    "endReason": null
  }
}
```

The exact nesting and state names can follow existing conventions. The required semantics are:

- `terminalId` identifies the PTY/shell.
- `agent.sessionId` is the opaque provider conversation ID used with `--resume-session`.
- `presetId` identifies which agent must resume it.
- `resumable` is false when the preset has no resume contract or no usable persisted session.
- Agent liveness comes from the binding/hook lifecycle, not merely from an open PTY.
- An ended agent in a still-open shell is distinguishable from a working or awaiting-input agent.
- The CLI does not interpret or normalize provider session IDs.

### Primary use case

An issue tracker keeps one unfinished work item bound to one workspace, agent preset, and opaque agent session ID. When the work becomes blocked or parked, it closes the terminal and releases capacity while preserving the conversation identity. A later issue comment creates a new terminal with `--resume-session <opaque-id>` and reaches the same Codex, Claude, or other conversation.

### Acceptance criteria

- [ ] `agents create --json` returns `terminalId` separately from the provider-neutral agent binding.
- [ ] A supported CLI command can retrieve the binding and liveness for an existing or recently ended terminal.
- [ ] `agentSessionId` round-trips through `--resume-session` for Claude and Codex in automated coverage.
- [ ] A provider with no resume arguments reports `resumable: false`.
- [ ] A provider that exits while the shell remains open is not reported as working.
- [ ] Existing terminal-oriented fields remain backwards compatible or receive a documented migration.
- [ ] CLI reference documentation explains terminal session ID versus agent session ID.

Related: #5126 tracks a broader CLI-readable terminal location index; #5189 already consumes `TerminalAgentBinding.agentSessionId` inside the desktop app. This request is the narrower supported orchestration contract.

### PR DESCRIPTION
**Pull request by toddagent01**
## What & why

Closes #6980.

A Superset terminal ID identifies a shell. A Claude or Codex session ID identifies the agent conversation inside that shell. They are different IDs, but `agents create` returned only the terminal ID under the ambiguous name `sessionId`.

That caused two problems for integrations:

1. They could save a terminal ID and later pass it to Claude or Codex as though it could resume the conversation.
2. A shell could remain open after its agent exited, making the terminal look alive even though no agent was working.

This PR reports terminal identity and agent identity separately, and provides a supported way to retrieve the agent conversation and its real lifecycle state.

## What changes

- `agents create` now returns an explicit `terminalId` and an `agent` identity block.
- The existing `sessionId` field remains as a deprecated alias of `terminalId` for compatibility.
- Adds `superset agents get --workspace <id> --terminal <id>`.
- The new command reports the opaque Claude, Codex, or other-provider session ID, whether it is resumable, its lifecycle state, timestamps, and end reason.
- Agent state is derived once in `@superset/shared` and reused by the host service and desktop app.
- The SDK exposes the same read operation, and the existing MCP create result uses the shared identity type.

## What this enables

An integration can close a terminal to release capacity, preserve the agent conversation, and later ask Superset to resume that same conversation. It can also distinguish an ended agent from an open shell.

The provider session ID remains opaque. Callers do not inspect Claude or Codex files, and this PR does not add provider-specific logic outside Superset.

## Safety and compatibility

- No database migration is required; the host service already stores the provider session ID.
- Existing consumers may continue reading `sessionId` as the terminal ID.
- Automatic pane-restoration policy is unchanged. This PR exposes whether deliberate resume-by-ID is supported; it does not automatically resume ended agents.
- This PR does not implement a Linear integration. It exposes a general CLI, SDK, and host-service contract that any integration can use.

## How I tested it

- `bun run lint`
- `bun run typecheck` — 38/38 packages
- Release, version, and i18n checks
- 19 new targeted tests
- Shared package: 851 passing
- CLI package: 147 passing
- Affected host-service suites: 120 passing
- A live host-service and PTY round trip exercised real Claude and Codex lifecycle payloads.
- After the provider ended while its shell remained open, `agents get` reported the agent as ended and the terminal as active.
- The stored provider ID was then passed through each provider's real resume arguments in a newly launched process.
- A preset without resume arguments correctly reported `resumable: false`.

The wider host-service run has the same 338 resource-contention failures on this branch and upstream `main`; every affected suite passes in isolation and this branch adds no new failures.

No screenshot is included because this change adds no new UI; the desktop change delegates its existing status calculation to the shared implementation.

## Checklist

- [x] PR title follows conventional commits
- [x] `bun run lint` and `bun run typecheck` pass
- [x] Allow edits from maintainers is enabled

### CODE REVIEW

**Review by cactuscrawford — APPROVED** [review]

**Comment by toddagent01** [comment]
Hi @Kitenite — this first-time-contributor PR is ready for upstream review, but GitHub Actions is waiting for maintainer approval. It is a self-contained agent-session identity change: local checks, live Claude/Codex lifecycle evidence, a linked issue, and maintainer-edit permission are all in place. Could you approve the workflow run and review when convenient? #6986 is a separate workspace-link change and is not required for this PR.
